### ISSUE TITLE
How I play my live stream on multiple website? Like, site1.com, site2.com

### ISSUE THREAD

**Issue by RtJahid** [Abdisalan/blog-code-examples#12]

**Comment by p01t0t0** [comment]
Have you come up with a solution @RtJahid ?
Please let me know if you did.

Maybe we could use [iframes](https://www.w3schools.com/tags/tag_iframe.ASP) for that?

**Comment by RtJahid** [comment]
no sir, I don't have solutionplz, guide me 
    On Sunday, December 12, 2021, 02:59:54 PM GMT+6, p01t0t0 ***@***.***> wrote:  
 
 


Have you come up with a solution @RtJahid ?
Please let me know if you did.

Maybe we could use iframes for that?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
