### ISSUE TITLE
Just I'm interesting why -1 ? 

### ISSUE THREAD

**Issue by aiandev** [Abdisalan/blog-code-examples#4]
https://github.com/Abdisalan/blog-code-examples/blob/8b40b9841b9f03271f3c35847618d46fbbd4ba44/http-video-stream/index.js#L24

**Comment by Abdisalan** [comment]
@aiandev bytes are zero indexed. So the last byte is `videoSize - 1`.
Similar to how you loop over an array, there are `array.length` items but the index of the last item is `array.length - 1`
